### ISSUE TITLE
Home page -Bug

### ISSUE THREAD

**Issue by alexdeathway** [niteshsinha17/GameZilla#4]
Home page appears blank after new user logs in.
//Development server.

**Comment by niteshsinha17** [comment]
You need to run `python manage.py create_games`. It creates game entry in the database.

**Comment by niteshsinha17** [comment]
I haven't mentioned it yet in the readme. 
Also if you want to test it locally. You will need to run redis server too.

**Comment by niteshsinha17** [comment]
thanks for responding on it.

**Comment by alexdeathway** [comment]
ok
